name: Node CI

on: [push, pull_request]

jobs:
  lint_and_test:
    name: Run lint and test on node ${{ matrix.node-version }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn, lint, and test
      run: |
        yarn --frozen-lockfile
        yarn lint
        yarn test
